export const Images = {
    logo: require('./Logo.png'),
    hamburger: require('./Hamburger.png'),
    header: require('./Header.png'),
    user: require('./User.png'),
    time: require('./Time.png'), 
    edit: require('./Edit.png'),
    search: require('./Search.png'),
    generateOrder: require('./GenerateOrder.png'),
    trainingLevels: require('./TrainingLevels.png'),
    certificates: require('./Certificates.png'),
    news: require('./News.png'),
    about: require('./about.jpg'),
    settings: require('./settings.png'),
    power:require('./power.png'),
    send: require('./send.png'),
    true: require('./true.png'),
    false: require('./false.png'),
    userGray: require('./userGray.png'),
    congrats: require('./Congratulations.png'),
    falseWhite: require('./falseWhite.png'),
    chevronDown: require('./chevron-down.png'),
    searchWhite: require('./searchWhite.png'),
    logoTP: require('./LogoTP.png')
};
